package com.oms.sdsauctionbid.utils;

public enum UserTypeName {
    SUPER_ADMIN,
    SUPER_ADMIN_BUSINESS_DEVELOPER,
    DISTRIBUTOR,
    DISTRIBUTORS_BUSINESS_DEVELOPERS,
    SUB_DISTRIBUTOR,
    SUB_DISTRIBUTORS_BUSINESS_DEVELOPERS,
    DEALERS,
    TRADERS,
    MOBILE_TRADERS,
    SUNDRY
    }
